apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
        - name: ollamamodels
          persistentVolumeClaim:
            claimName: pvc-ollama
      containers:
      - name: ollama
        image: ollama/ollama:latest
        resources:
          limits:
            cpu: "6000m"
        volumeMounts:
          - name: ollamamodels
            mountPath: /root/.ollama
        ports:
        - name: ollama
          containerPort: 11434
